[project]
name = "mbot"
version = "0.1.0"
description = "mbot is an AI-powered GitHub PR reviewer built with FastAPI."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.115.8",
    "google-genai>=1.2.0",
    "pyjwt[crypto]>=2.10.1",
    "uvicorn>=0.34.0",
]
